# Generated by Django 5.1.2 on 2024-11-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_name', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_number', models.CharField(max_length=15)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_name', models.CharField(max_length=100)),
                ('dropoff_number', models.CharField(max_length=15)),
                ('items_worth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_parcel_name', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(choices=[('dispatch', 'Dispatch'), ('bus', 'Bus')], max_length=10)),
            ],
        ),
    ]
