# Generated by Django 5.1.2 on 2024-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0002_delivery_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
