# Generated by Django 5.1.2 on 2024-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0003_delivery_weight_alter_delivery_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
