# Generated by Django 5.1.2 on 2025-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0004_alter_delivery_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('dispatch', 'Dispatch'), ('bus', 'Bus')], default='dispatch', max_length=10),
        ),
    ]
