# Generated by Django 5.1.2 on 2025-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Main keyword for SEO', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Max 160 characters', max_length=160),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Max 60 characters', max_length=60),
        ),
    ]
