# Generated by Django 5.1.2 on 2025-05-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='blog.blog')),
            ],
        ),
    ]
